services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    depends_on:
      - auth
      - user

  auth:
    build:
      context: ./mock
    ports:
      - "9001:5678"

  user:
    build:
      context: ./mock
    ports:
      - "9002:5678"
